# Generated by Django 2.1.7 on 2019-05-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_Rating',
            field=models.IntegerField(default=0),
        ),
    ]
