# Generated by Django 2.1.7 on 2019-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_Rating',
            field=models.FloatField(default=0),
        ),
    ]
